development:
  adapter: postgresql
  encoding: unicode
  database: preemptivehack_development
  host: localhost
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: preemptivehack_test
  host: localhost
  pool: 5
