development:
  adapter: postgresql
  encoding: unicode
  database: preemptivehack_development
  username: vagrant

test:
  adapter: postgresql
  encoding: unicode
  database: preemptivehack_test
  username: vagrant